# Generated by Django 4.2.4 on 2023-08-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bloc', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'entreprise")),
            ],
        ),
    ]
