# Generated by Django 4.2.4 on 2023-08-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la section')),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conso.bloc')),
            ],
        ),
    ]
