# Generated by Django 4.2.4 on 2023-08-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0003_variable_dispositif_consommation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='bloc',
        ),
        migrations.AddField(
            model_name='dispositif',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro serie'),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='dispositif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.dispositif'),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.section'),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.variable'),
        ),
        migrations.DeleteModel(
            name='Bloc',
        ),
    ]
