# Generated by Django 4.2.4 on 2023-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0004_remove_section_bloc_dispositif_numero_serie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'entreprise ou de la société")),
                ('telephone', models.IntegerField(verbose_name='Numéro de téléphone')),
                ('domaine_act', models.CharField(blank=True, max_length=100, null=True, verbose_name="Domaine d'activité")),
                ('localite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localisation')),
            ],
        ),
    ]
