# Generated by Django 4.2.4 on 2023-08-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0005_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de votre entreprise'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='mot_de_passe',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='domaine_act',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Domaine d'activité de votre entreprise"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='localite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localisation de votre entreprise'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
