# Generated by Django 4.2.4 on 2023-08-28 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conso', '0006_entreprise_email_entreprise_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='email',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='domaine_act',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='localite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localisation'),
        ),
    ]
