# Generated by Django 4.2.4 on 2023-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0007_remove_entreprise_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositif',
            name='source_eau',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Source d'eau"),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
