# Generated by Django 4.2.4 on 2023-09-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0008_dispositif_source_eau_alter_consommation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.entreprise'),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositif',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
