# Generated by Django 4.2.4 on 2023-09-07 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conso', '0009_section_entreprise_alter_dispositif_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='email',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
