# Generated by Django 4.2.4 on 2023-09-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0010_entreprise_email_alter_entreprise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
