# Generated by Django 4.2.4 on 2023-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0012_categorie_remove_entreprise_email_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='quantite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='domaine_act',
            field=models.CharField(blank=True, default="Domaine d'activité", max_length=100, null=True, verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='localite',
            field=models.CharField(blank=True, default='Localite de la societe', max_length=100, null=True, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom_societe',
            field=models.CharField(blank=True, default='Nom de la societe', max_length=100, null=True, verbose_name="Nom de l'entreprise ou de la société"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(blank=True, default='00000000', max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
