# Generated by Django 4.2.4 on 2023-09-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0013_alter_consommation_quantite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
