# Generated by Django 4.2.4 on 2023-09-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0015_alter_dispositif_nom_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositif',
            name='nom_lieu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Le lieu où se trouve le dispositif'),
        ),
    ]
