# Generated by Django 4.2.4 on 2023-09-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0017_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
