# Generated by Django 4.2.4 on 2023-09-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0021_budget_description_budget_solde_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.entreprise'),
        ),
    ]
