# Generated by Django 4.2.4 on 2023-09-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0022_alert_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='intitule_commande',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
