# Generated by Django 4.2.4 on 2023-09-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0023_depense_intitule_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='solde',
        ),
        migrations.DeleteModel(
            name='Depense',
        ),
    ]
